#general

SECRET_KEY = 'propertY12345!'
RECAPTCHA_PUBLIC_KEY = '6Lc_8QQaAAAAAD_zxfpY13827mX4WTHXf-_DgHl_'
RECAPTCHA_PRIVATE_KEY = '6Lc_8QQaAAAAANGwLaNEstJtOqJN1qJxEcCLTMph'
Testing = True

#db
SQLALCHEMY_DATABASE_URI = 'sqlite:///site.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False

